# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'AKMediaViewerExample' do
  pod 'ASBPlayerScrubbing'
  pod 'AKMediaViewer', :path => '../AKMediaViewer.podspec'
end
